export const Locations = {
    MAIN: 'MAIN_PAGE',
    LANDING: 'LANDING_PAGE',
    PROFILE: 'PROFILE_PAGE'
}

export const ActionTypes = {
    GO_TO_PAGE: 'GO_TO_PAGE',
    UPDATE_HEADLINE: 'UPDATE_HEADLINE',
    REMOVE_FOLLOWER: 'REMOVE_FOLLOWER',
    ADD_FOLLOWER: 'ADD_FOLLOWER',
    ADD_ARTICLE: 'ADD_ARTICLE',
    CHANGE_FILTER: 'CHANGE_FILTER'
}